spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 1000

  profiles:
    include: dev

url:
  base: http://localhost:3000

springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: 'true'
  swagger-ui:
    groups-order: DESC
    displayRequestDuration: 'true'
    path: /swagger-ui.html
  cache:
    disabled: 'true'
