server:
  port: 8080
spring:

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console
  profiles:
    include: dev

url:
  base: http://localhost:3000


springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: 'true'
  swagger-ui:
    groups-order: DESC
    displayRequestDuration: 'true'
    path: /swagger-ui.html
  cache:
    disabled: 'true'
